blank_issues_enabled: false
contact_links:
  - name: Nucleus Support Discord
    url: https://discord.gg/A9QHG5H
    about: If you require support, please visit our Discord server and ask there. Do not create support issues.
