# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - v2/S7

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build docGen

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        USER: ${{ github.actor }}
        KEY: ${{ secrets.GITHUB_TOKEN }}
        REPO: "NucleusPowered/Nucleus"

    - name: Upload Plugin
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: output/*-plugin.jar
    - name: Upload API
      uses: actions/upload-artifact@v2
      with:
        name: API
        path: output/*-API.jar
    - name: Upload Javadocs
      uses: actions/upload-artifact@v2
      with:
        name: Javadocs
        path: output/*-javadocs.jar
    - name: Upload YAML
      uses: actions/upload-artifact@v2
      with:
        name: YML
        path: output/*.yml
    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: Release Notes
        path: output/*.md
