# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  push:
    tags:
      - '[2-9]*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Github Actions Environment Variable (Version)
      run: ./gradlew setGithubActionsVersion

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Doc Gen
      run: ./gradlew docGen

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USER: ${{ github.actor }}
        KEY: ${{ secrets.GITHUB_TOKEN }}
        REPO: "NucleusPowered/Nucleus"

    - name: Upload Plugin
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus Plugin
        path: output/*-plugin.jar
    - name: Upload API
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus API
        path: output/*-API.jar
    - name: Upload Javadocs
      uses: actions/upload-artifact@v2
      with:
        name: Nucleus Javadocs
        path: output/*-javadocs.jar
    - name: Upload YAML
      uses: actions/upload-artifact@v2
      with:
        name: YML files from DocGen
        path: output/*.yml
    - name: Upload Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: Release Notes
        path: output/*.md
  docs:
    runs-on: ubuntu-latest